#2F IP settings
# BACKEND_SERVER_IP: 192.168.10.115:5000
# CLOUDXR_CLIENT_IP: 172.16.0.213
# CLOUDXR_SERVER_MANAGER_IP: 172.16.10.120
# LOCAL_IP: 192.168.10.120

#3F IP settings - Self
# BACKEND_SERVER_IP: 172.16.0.189:5000
#3F IP settings - Jared
BACKEND_SERVER_IP: 172.16.0.25:5000
STREAM_SERVER_IP: 172.16.0.189:5000
GAMESERVER_IP:  0.0.0.0
GAMESERVER_PORT:  8080
CLOUDXR_CLIENT_IP: 172.16.0.213
CLOUDXR_SERVER_MANAGER_IP: 172.16.0.3
LOCAL_IP: 172.16.0.3

#------------------------------------------------------
PROJECTNAME: Project_VRCloudGaming
PROJECTPATH: null
